spring:
  application:
    name: mandalin

  datasource:
    url: jdbc:mysql://localhost:3306/mandalin-operation
    username: root
    password: Mtltmxpa123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always